version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=m111202'
      - 'POSTGRES_DB=aloteq'

  springbootapp:
    build: ./
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres:5432/aloteq'
    ports:
      - "8080:8080"
    depends_on:
      - postgres